version: "2.3"

services:
  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/quarkus-demo-jvm:latest
    mem_limit: 128m
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://quarkus-db:5432/quarkus
    ports:
      - "8080:8080"  # the HTTP endpoint
    networks:
      - quarkus 
networks:
   quarkus:
    driver: bridge

