apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-quarkus-service
  labels:
    app: trainer-quarkus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer-quarkus-service
  template:
    metadata:
      labels:
        app: trainer-quarkus-service
        io.kompose.network/quarkus: "true"
    spec:
      containers:
      - name: trainer-quarkus-service
        image: public.ecr.aws/e8v6d9d7/quarkus-demo-jvm:1.0.1 # quarkus-demo-jvm:1.0.0 # sha256:76bd2f142864206b3a862a006b1d89d28e13973341004e6fb58a010342c62abd  # cgs/quarkus-demo-jvm:latest
        ports:
         - containerPort: 8080
        env:
        - name: POSTGRES_DB
          value: simplechat
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: trainer-quarkus-db-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trainer-quarkus-db-secret
              key: postgres-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: trainer-quarkus-demo-config
              key: trainer-quarkus-db
        #- name: QUARKUS_DATASOURCE_JDBC_URL
        #   value: jdbc:postgresql://quarkus-db:5432/simplechat
---
apiVersion: v1
kind: Service
metadata:
  name: trainer-quarkus-service
  labels:
    app: trainer-quarkus-service
spec:
  type: LoadBalancer  # NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30912  # must be between 30000 and 32767
  selector:
    app: trainer-quarkus-service


