apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-quarkus-db
  labels:
    app: trainer-quarkus-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer-quarkus-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trainer-quarkus-db
    spec:
      containers:
        - name: trainer-quarkus-db
          image: postgres:10.5
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: simplechat
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: trainer-quarkus-db-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: trainer-quarkus-db-secret
                key: postgres-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: trainer-quarkus-db-v
      volumes:
      - name: trainer-quarkus-db-v
        persistentVolumeClaim:
          claimName: trainer-quarkus-db-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: trainer-quarkus-db
spec:
  selector:
    app: trainer-quarkus-db
  ports:
    - protocol: TCP
      port: 5432  # maps any incomming port 5432  A Service can map any incoming port to a targetPort.
      targetPort: 5432 #  By default and for convenience, the targetPort is set to the same value as the port field.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trainer-quarkus-db-claim0
  labels:
    app: trainer-quarkus-db
spec:
  accessModes:
    - ReadWriteOnce # volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: 100Mi

